# Site wide configuration

name: Lisbeth Hamlin
description: "My art is dedicated to fostering an appreciation of cultural diversity."
logo:
teaser:
locale: en_US
timezone: America/Chicago
url: https://www.lisbethhamlin.com

#Lib versions
photoswipe-version: 4.1.1
jquery-version: 2.2.4
imagesloaded-version: 4.1.0
masonry-version: 4.1.0
seedrandom-version: 2.4.2

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-feed

# Site owner
author:
  name: Lisbeth Hamlin
  email: betsydhamlin@yahoo.com
  twitter:
  google:
    ad-client:
    ad-slot:
    tracking-id: UA-58096804-1
  bio:
  avatar:
disqus-shortname:

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config",
          "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project",
          "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md",
          "LICENSE", "node_modules", "Gruntfile.js", "package.json", "CNAME"]
