# Site wide configuration

title: Lisbeth Hamlin
description: "My art is dedicated to fostering an appreciation of cultural diversity."
logo: 
teaser: 
locale: en_US
front-page-posts: 8 # number of posts to show on the main page
url: //www.lisbethhamlin.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap

# Site owner
owner:
  name: Lisbeth Hamlin
  email: info@lisbethhamlin.com
  twitter:
  google:
    ad-client:
    ad-slot:
    tracking-id: UA-58096804-1
  bio:
  avatar:
disqus-shortname:

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
