name: CI
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install, build, test
        run: |
          npm ci && npm run build
          JEKYLL_ENV=production bundle exec jekyll build
          htmlproofer ./_site --check-html --allow-hash-href --disable-external

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: master # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          clean: true
          single-commit: true

